# -*- coding: utf-8 -*-
"""Predictive Cricket Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNBpdwu59jYXG23DpQ7tktiiXJUo8SXU
"""

#Predictive Cricket
import random as r
def play(over,target):
  wicket_left=10
  run=0
  balls_left=over*6
  while(balls_left>0 and wicket_left>0 and run<target):
    ch=int(input("Enter a number in between 1-50: "))
    x=r.randint(1,50)
    if x>50 or x<1:
      print("Invalid Input, try again.")
    elif abs(x-ch)<5:
      print("Amazing!! You scored 6 runs!!!")
      run+=6
      balls_left-=1
    elif abs(x-ch)>=5 and abs(x-ch)<10:
      print("Congrats!! You scored 4 runs!")
      run+=4
      balls_left-=1
    elif abs(x-ch)>=10 and abs(x-ch)<15:
      print("Great!! You scored 3 runs!")
      run+=3
      balls_left-=1
    elif abs(x-ch)>=15 and abs(x-ch)<20:
      print("Good! You scored 2 runs!")
      run+=2
      balls_left-=1
    elif abs(x-ch)>=20 and abs(x-ch)<25:
      print("Nice, You scored 1 run!")
      run+=1
      balls_left-=1
    elif abs(x-ch)>=25 and abs(x-ch)<30:
      print("You got a Dot ball, no runs this time..")
      balls_left-=1
    elif abs(x-ch)>=30:
      print("It’s a wicket..!")
      wicket_left-=1
      balls_left-=1
  print("Total runs =", run)
  print("Total balls left =", balls_left)
  print("Total wickets left =", wicket_left)
  if wicket_left<0 and run<target:
    print("You have 0 wickets and you didn't reach your target runs, you lose!!!")
  elif balls_left<0 and run<target:
    print("You have no more balls left and you didn't reach your target runs, you lose!!!")
  elif run>=target:
    print("YOU WON!! You reached your target runs!!!")
  input("Press Enter to go back to the options menu: ")
def gameloop():
  while(True):
    print('''Enter 1 to play the game.
Enter 2 to show the rules.
Enter 3 to exit.  ''')
    i=int(input(": "))
    if i==1:
      over=int(input("How many overs do you require? : "))
      target=int(input("What is your target runs to achieve? : "))
      play(over,target)
    elif i==2:
      print('''1.This is a simple predictive cricket game.
2.In this game you have to predict a number between 1 to 50
3.If your prediction is closure to 5 consecutive number to the computer generated
number, then you will get 6 runs
4.If your prediction is between 5 to 10 consecutive numbers to the computer
generated number, then you will get 4 runs
5.If your prediction is between 10 to 15 consecutive numbers to the computer
generated number, then you will get 3 runs
6.If your prediction is between 15 to 20 consecutive numbers to the computer
generated number, then you will get 2 runs
7.If your prediction is between 20 to 25 consecutive numbers to the computer
generated number, then you will get 1 runs
8.If your prediction is between 25 to 30 consecutive numbers to the computer
generated number, then you will get 0 runs
9.If your prediction is over 30 consecutive numbers to the computer generated
number, then you will out
10.The computer generated number is the randomly generated number by
computer''')
      input("Press Enter to go back: ")
    elif i==3:
      break
    else:
      print("Invalid input, please only enter the options given.")
gameloop()